os:
  - linux

language: node_js
before_script:
  - yarn global add gatsby
node_js:
  - "12.16.3"
deploy:
  provider: script
  script: yarn install && yarn travisdeploy
  skip_cleanup: true
  on:
    branch: master
